[package]
name = "surge-ping"
version = "0.1.0"
authors = ["kolapapa <milk346512016@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/kolapapa/surge-ping"
description = "Asynchronous ICMP ping library"
keywords = ["tokio", "icmp", "ping"]
categories = ["network-programming", "asynchronous"]

[dependencies]
packet = "0.1.4"
rand = "0.8"
socket2 = "0.3"
structopt = "0.3"
thiserror = "1.0"
tokio = { version = "1.0", features = ["time", "macros"] }

[dev-dependencies]
log = "0.4"
pretty_env_logger = "0.4"
tokio = { version = "1.0", features = ["full"] }

[[example]]
name = "simple"
