[package]
name = "surge"
version = "0.1.0"
authors = ["kola"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.5.2"
packet = "0.1.4"
parking_lot = "0.11.1"
rand = "0.8.0"
socket2 = "0.3.19"
tokio = { version = "1.0.1", features = ["full"] }
