[package]
name = "surge-ping"
version = "0.1.5"
authors = ["kolapapa <milk346512016@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/kolapapa/surge-ping"
description = "Asynchronous ICMP ping library"
keywords = ["tokio", "icmp", "ping"]
categories = ["network-programming", "asynchronous"]

[dependencies]
log = "0.4.11"
packet = "0.1.4"
parking_lot = "0.11.1"
rand = "0.8.0"
socket2 = "0.3.19"
thiserror = "1.0.23"
tokio = { version = "1.0.1", features = ["time", "macros"] }

[dev-dependencies]
log = "0.4"
structopt = "0.3"
pretty_env_logger = "0.4"
tokio = { version = "1.0", features = ["full"] }

[[example]]
name = "simple"

[[example]]
name = "cmd"

[[example]]
name = "multi_ping"
